# azure-pipelines.yml
trigger:
- main  # Adjust the branch name as needed

pool:
  name: 'mysecondagent'  # Replace with the name of your self-hosted agent pool
  
steps:
- script: |
    echo "Running on a self-hosted agent..."
  displayName: "Run Bash Script"

