# azure-pipelines.yml
trigger:
- main  # Adjust the branch name as needed

pool:
  name: 'SelfHostedPool'  # Replace with the name of your self-hosted agent pool
  
steps:
- script: |
    echo "Running on a self-hosted agent..."
    chmod +x script.sh
    ./script.sh
  displayName: "Run Bash Script"

